openrem/openremproject/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^openrem/', include('remapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # Login / logout.
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'remapp.views.logout_page'),

)

openrem/remapp/urls.py
#    OpenREM - Radiation Exposure Monitoring tools for the physicist
#    Copyright (C) 2012,2013  The Royal Marsden NHS Foundation Trust
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    Additional permission under section 7 of GPLv3:
#    You shall not make any use of the name of The Royal Marsden NHS
#    Foundation trust in connection with this Program in any press or 
#    other public announcement without the prior written consent of 
#    The Royal Marsden NHS Foundation Trust.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
..  module:: urls.
    :synopsis: Module to match URLs and pass over to views or export modules.

..  moduleauthor:: Ed McDonagh

"""

from django.conf.urls import patterns, include, url
from django_filters.views import FilterView
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from remapp.models import AccumProjXRayDose, GeneralStudyModuleAttr


urlpatterns = patterns('remapp.views',

    url(r'^$',
        'openrem_home'),

    url(r'^rf/$',
        'rf_summary_list_filter'),
    url(r'^rf/(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=GeneralStudyModuleAttr,
            template_name='remapp/rfdetail.html'))),

    url(r'^ct/$',
        'ct_summary_list_filter'),
    url(r'^ct/(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=GeneralStudyModuleAttr,
            template_name='remapp/ctdetail.html'))),

    url(r'^dx/$',
        'dx_summary_list_filter'),
    url(r'^dx/(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=GeneralStudyModuleAttr,
            template_name='remapp/dxdetail.html'))),

    url(r'^mg/$',
        'mg_summary_list_filter'),
    url(r'^mg/(?P<pk>\d+)/$',
        login_required(DetailView.as_view(
            model=GeneralStudyModuleAttr,
            template_name='remapp/mgdetail.html'))),

    url(r'^viewdisplaynames/$',
        'display_names_view'),

    url(r'^delete/(?P<pk>\d+)$', 'study_delete', name='study_delete'),
    url(r'^admin/sizeupload$', 'size_upload', name='size_upload'),
    url(r'^admin/sizeprocess/(?P<pk>\d+)/$', 'size_process', name='size_process'),
    url(r'^admin/sizeimports', 'size_imports', name='size_imports'),
    url(r'^admin/sizedelete', 'size_delete', name='size_delete'),
    url(r'^admin/sizeimport/abort/(?P<pk>\d+)$', 'size_abort'),
    url(r'^updatedisplayname/$', 'display_names_view', name='display_names_view'),
    url(r'^updatedisplayname/(?P<pk>\d+)$', 'display_name_update', name='display_name_update'),
)

urlpatterns += patterns('remapp.exports.exportviews',
    url(r'^export/$', 'export'),
    url(r'^exportctcsv1/$', 'ctcsv1'),
    url(r'^exportctxlsx1/$', 'ctxlsx1'),
    url(r'^exportdxcsv1/$', 'dxcsv1'),
    url(r'^exportdxxlsx1/$', 'dxxlsx1'),
    url(r'^exportflcsv1/$', 'flcsv1'),
    url(r'^exportrfxlsx1/$', 'rfxlsx1'),
    url(r'^exportrfopenskin/(?P<pk>\d+)$', 'rfopenskin'),
    url(r'^exportmgcsv1/$', 'mgcsv1'),
    url(r'^exportmgnhsbsp/$', 'mgnhsbsp'),
    url(r'^download/(?P<file_name>.+)$', 'download'),
    url(r'^deletefile/$', 'deletefile'),
    url(r'^export/abort/(?P<pk>\d+)$', 'export_abort'),
)

urlpatterns += patterns('remapp.exports',
    url(r'^xlsx/openrem/ct/',
        'xlsx.ctxlsx'),
)

urlpatterns += patterns('remapp.views',
    url(r'^charts_off/$',
        'charts_off'),
)

openrem/remapp/models.py
#    OpenREM - Radiation Exposure Monitoring tools for the physicist
#    Copyright (C) 2012,2013  The Royal Marsden NHS Foundation Trust
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    Additional permission under section 7 of GPLv3:
#    You shall not make any use of the name of The Royal Marsden NHS
#    Foundation trust in connection with this Program in any press or 
#    other public announcement without the prior written consent of 
#    The Royal Marsden NHS Foundation Trust.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
..  module:: models.
    :synopsis: Models to create the database tables and relationships.

..  moduleauthor:: Ed McDonagh

"""

# Following two lines added so that sphinx autodocumentation works. 
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'openremproject.settings'
from django.db import models


from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    DAYS = 'days'
    WEEKS = 'weeks'
    MONTHS = 'months'
    YEARS = 'years'
    TIME_PERIOD = (
        (DAYS, 'Days'),
        (WEEKS, 'Weeks'),
        (MONTHS, 'Months'),
        (YEARS, 'Years'),
    )

    MEAN = 'mean'
    MEDIAN = 'median'
    BOTH = 'both'
    AVERAGES = (
        (MEAN, 'mean'),
        (MEDIAN, 'median'),
        (BOTH, 'both'),
    )

    # This field is required.
    user = models.OneToOneField(User)

    # Flag to set whether median calculations can be carried out
    median_available = models.BooleanField(default=False,
                                           editable=False)

    plotAverageChoice = models.CharField(max_length=6,
                                         choices=AVERAGES,
                                         default=MEAN)

    # Plotting controls
    plotCharts = models.BooleanField(default=False)
    plotDXAcquisitionMeanDAP = models.BooleanField(default=True)
    plotDXAcquisitionFreq = models.BooleanField(default=False)
    plotDXAcquisitionMeankVp = models.BooleanField(default=False)
    plotDXAcquisitionMeanmAs = models.BooleanField(default=False)
    plotDXStudyPerDayAndHour = models.BooleanField(default=False)
    plotDXAcquisitionMeanDAPOverTime = models.BooleanField(default=False)
    plotDXAcquisitionMeanDAPOverTimePeriod = models.CharField(max_length=6,
                                                              choices=TIME_PERIOD,
                                                              default=MONTHS)

    plotCTAcquisitionMeanDLP = models.BooleanField(default=True)
    plotCTAcquisitionMeanCTDI = models.BooleanField(default=True)
    plotCTAcquisitionFreq = models.BooleanField(default=False)
    plotCTStudyMeanDLP = models.BooleanField(default=True)
    plotCTStudyFreq = models.BooleanField(default=False)
    plotCTRequestMeanDLP = models.BooleanField(default=False)
    plotCTRequestFreq = models.BooleanField(default=False)
    plotCTStudyPerDayAndHour = models.BooleanField(default=False)
    plotCTStudyMeanDLPOverTime = models.BooleanField(default=False)
    plotCTStudyMeanDLPOverTimePeriod = models.CharField(max_length=6,
                                                        choices=TIME_PERIOD,
                                                        default=MONTHS)

    displayCT = models.BooleanField(default=True)
    displayRF = models.BooleanField(default=True)
    displayMG = models.BooleanField(default=True)
    displayDX = models.BooleanField(default=True)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class UniqueEquipmentNames(models.Model):
    manufacturer = models.TextField(blank=True, null=True)
    institution_name = models.TextField(blank=True, null=True)
    station_name = models.CharField(max_length=32, blank=True, null=True)
    institutional_department_name = models.TextField(blank=True, null=True)
    manufacturer_model_name = models.TextField(blank=True, null=True)
    device_serial_number = models.TextField(blank=True, null=True)
    software_versions = models.TextField(blank=True, null=True)
    gantry_id = models.TextField(blank=True, null=True)
    display_name = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ('manufacturer', 'institution_name', 'station_name', 'institutional_department_name',
                           'manufacturer_model_name', 'device_serial_number', 'software_versions', 'gantry_id')

class SizeUpload(models.Model):
    sizefile = models.FileField(upload_to='sizeupload')
    height_field = models.TextField(blank=True, null=True)
    weight_field = models.TextField(blank=True, null=True)
    id_field = models.TextField(blank=True, null=True)
    id_type = models.TextField(blank=True, null=True)
    task_id = models.TextField(blank=True, null=True)
    status = models.TextField(blank=True, null=True)
    progress = models.TextField(blank=True, null=True)
    num_records = models.IntegerField(blank=True, null=True)
    logfile = models.FileField(upload_to='sizelogs/%Y/%m/%d', null=True)
    import_date = models.DateTimeField(blank=True, null=True)
    processtime = models.FloatField(blank=True, null=True)


class Exports(models.Model):
    """Table to hold the export status and filenames
    """
    task_id = models.TextField()
    filename = models.FileField(upload_to='exports/%Y/%m/%d', null=True)
    status = models.TextField(blank=True, null=True)
    progress = models.TextField(blank=True, null=True)
    modality = models.CharField(max_length=16, blank=True, null=True)
    num_records = models.IntegerField(blank=True, null=True)
    export_type = models.TextField(blank=True, null=True)
    export_date = models.DateTimeField(blank=True, null=True)
    processtime = models.DecimalField(max_digits=30, decimal_places=10, blank=True, null=True)


class ContextID(models.Model):
    """Table to hold all the context ID code values and code meanings.
    
    + Could be prefilled from the tables in DICOM 3.16, but is actually populated as the codes occur. \
    This assumes they are used correctly.
    
    """    
    code_value = models.CharField(max_length=16)
    code_meaning = models.TextField(blank=True, null=True)
    cid_table = models.CharField(max_length=16, blank=True)

    def __unicode__(self):
        return self.code_meaning

    class Meta:
        ordering = ['code_value']


class GeneralStudyModuleAttr(models.Model):  # C.7.2.1
    """General Study Module C.7.2.1
    
    Specifies the Attributes that describe and identify the Study 
    performed upon the Patient.
    
    From DICOM Part 3: Information Object Definitions Table C.7-3

    Additional to the module definition:
        * performing_physician_name
        * operator_name
        * modality_type
        * procedure_code_value_and_meaning
        * requested_procedure_code_value_and_meaning
    """
    study_instance_uid = models.TextField(blank=True, null=True)
    study_date = models.DateField(blank=True, null=True)
    study_time = models.TimeField(blank=True, null=True)
    study_workload_chart_time = models.DateTimeField(blank=True, null=True)
    referring_physician_name = models.TextField(blank=True, null=True)
    referring_physician_identification = models.TextField(blank=True, null=True)
    study_id = models.CharField(max_length=16, blank=True, null=True)
    accession_number = models.CharField(max_length=16, blank=True, null=True)
    study_description = models.TextField(blank=True, null=True)
    physician_of_record = models.TextField(blank=True, null=True)
    name_of_physician_reading_study = models.TextField(blank=True, null=True)
    # Possibly need a few sequences linked to this table...
    # Next three don't belong in this table, but they don't belong anywhere in a RDSR!
    performing_physician_name = models.TextField(blank=True, null=True)
    operator_name = models.TextField(blank=True, null=True)
    modality_type = models.CharField(max_length=16, blank=True, null=True)
    procedure_code_value = models.CharField(max_length=16, blank=True, null=True)
    procedure_code_meaning = models.TextField(blank=True, null=True)
    requested_procedure_code_value = models.CharField(max_length=16, blank=True, null=True)
    requested_procedure_code_meaning = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return self.study_instance_uid


class ProjectionXRayRadiationDose(models.Model):  # TID 10001
    """Projection X-Ray Radiation Dose template TID 10001
    
    From DICOM Part 16:
        This template defines a container (the root) with subsidiary content items, each of which represents a
        single projection X-Ray irradiation event entry or plane-specific dose accumulations. There is a defined
        recording observer (the system or person responsible for recording the log, generally the system). A
        Biplane irradiation event will be recorded as two individual events, one for each plane. Accumulated
        values will be kept separate for each plane.
    
    """
    general_study_module_attributes = models.ForeignKey(GeneralStudyModuleAttr)
    procedure_reported = models.ForeignKey(
        ContextID, blank=True, null=True, related_name='tid10001_procedure')
    has_intent = models.ForeignKey(

openrem/remapp/templates/remapp/celerytest.html
<!DOCTYPE html>
<html>
<head>
 <title>Celery testing</title>
 <script src="{{ STATIC_URL }}js/jquery-1.11.0.min.js"></script>
 <style>
  .progress {
   width:50%;
   background:yellow;
  }
  .bar {
   height:15px;
   width:0%;
   background:tomato;
   text-align:right;
  }
 </style>
</head>
<body>
 <h1>Create 1000 objects in 1 click!</h1>
 
 <div id="container">
  <div id="action">
   <button id="do-task">Click here!</button>
  </div>
  
  <div class="progress_container">
   
   <div class="current-task">
    <h4>{% if task_id %} Task ID: {{ task_id }} {% endif %}</h4>
   </div>
   
   <div class="status"></div>
   {% if task_id %}
   <div class="progress">
    <div class="bar"></div>
   </div>
   {% endif %}
  </div>
  
 </div>
 {% if task_id %}
 <script type="text/javascript">
  jQuery(document).ready(function() {
   
   // poll state of the current task
   var PollState = function(task_id) {
    jQuery.ajax({
     url: "poll_state",
     type: "POST",
     data: "task_id=" + task_id,
    }).done(function(task){
     console.log(task);
     if (task.process_percent) {
      jQuery('.bar').css({'width': task.process_percent + '%'});
      jQuery('.bar').html(task.process_percent + '%')
     } else {
      jQuery('.status').html(task);
     };
     
     // create the infinite loop of Ajax calls to check the state
     // of the current task
     PollState(task_id);
    });
   }
   
   PollState('{{ task_id }}');
  });
 </script>
 {% endif %}
 <script type="text/javascript">
  jQuery('#do-task').click( function() {
   jQuery.ajax({
    url: "do_task",
    data: {},
    success: function(){
     jQuery.ajax({
      url: "",
      context: document.body,
      success: function(s, x) {
       jQuery(this).html(s);
      }
     });
    }
   })
  });
 </script>
 
</body>
</html>

openrem/remapp/templates/remapp/displaynameview.html
{% extends "remapp/base.html" %}


{% block navbar %}
  {% if request.user.userprofile.displayCT %}<li><a href="/openrem/ct">CT</a></li>{% endif %}
  {% if request.user.userprofile.displayRF %}<li><a href="/openrem/rf">Fluoroscopy</a></li>{% endif %}
  {% if request.user.userprofile.displayMG %}<li><a href="/openrem/mg">Mammography</a></li>{% endif %}
  {% if request.user.userprofile.displayDX %}<li><a href="/openrem/dx">Radiography</a></li>{% endif %}
{% endblock %}


{% block toprow %}
  {% load pagination_tags %}
  <p>
    There are {{ name_list.count }} entries in this table.
    {% if admin.adminperm %} Click on a row to edit the display name.{% endif %}
  </p>
{% endblock %}


{% block mainblock %}
  {% if admin.adminperm %}
  <script>
  jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
    });
  });
  </script>
  {% endif %}

  <table class="table table-bordered table-hover row-clickable">
    <row>
      <th>Display name</th><th>Institution</th><th>Department</th><th>Manufacturer</th><th>Model</th><th>Station name</th><th>Serial no.</th><th>Software version</th><th>Gantry ID</th>
    </row>
    {% for eachrow in name_list.values %}
      <tr class="clickable-row" data-href="{% url 'display_name_update' eachrow.id %}">
        <td><a style="text-decoration: none">{{ eachrow.display_name }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.institution_name }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.institutional_department_name }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.manufacturer }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.manufacturer_model_name }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.station_name }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.device_serial_number }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.software_versions }}</a></td>
        <td><a style="text-decoration: none">{{ eachrow.gantry_id }}</a></td>
      </tr>
    {% endfor %}
  </table>

  {% paginate %}

{% endblock %}

openrem/remapp/templates/remapp/dxdetail.html
{% extends "remapp/base.html" %}
{% block navbar %}
            {% if request.user.userprofile.displayCT %}<li><a href="/openrem/ct">CT</a></li>{% endif %}
            {% if request.user.userprofile.displayRF %}<li><a href="/openrem/rf">Fluoroscopy</a></li>{% endif %}
            {% if request.user.userprofile.displayMG %}<li><a href="/openrem/mg">Mammography</a></li>{% endif %}
            {% if request.user.userprofile.displayDX %}<li class="active"><a href="/openrem/dx">Radiography</a></li>{% endif %}
{% endblock %}


{% block mainblock %}		

<h1>Detail list of events</h1>

<ul>
    <li>Accession number: {{ generalstudymoduleattr.accession_number }}</li>
    <li>Study date: {{ generalstudymoduleattr.study_date }}</li>
    <li>Study time: {{ generalstudymoduleattr.study_time }}</li>
    <li>Study description: {{ generalstudymoduleattr.study_description }}</li>
    <li>Requested procedure: {{ generalstudymoduleattr.requested_procedure_code_meaning }}</li>
    <li>Patient age: {{ generalstudymoduleattr.patientstudymoduleattr_set.get.patient_age_decimal|floatformat:1 }}</li>
    <li>Patient height and weight: {{ generalstudymoduleattr.patientstudymoduleattr_set.get.patient_size|floatformat:0 }} cm, {{ generalstudymoduleattr.patientstudymoduleattr_set.get.patient_weight|floatformat:1 }} kg</li>
    <li>Hospital: {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.institution_name }}</li>
    <li>
        X-ray system:
        {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.manufacturer }} |
        {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.manufacturer_model_name }} |
        {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.station_name }}
    </li>
    <li>Study UID: {{ generalstudymoduleattr.study_instance_uid }}</li>
    <li>Test patient indicators? {{ generalstudymoduleattr.patientmoduleattr_set.get.not_patient_indicator }}</li>
    <li>Number of events: {{ generalstudymoduleattr.projectionxrayradiationdose_set.get.accumxraydose_set.get.accumintegratedprojradiogdose_set.get.total_number_of_radiographic_frames }}</li>
    <li>
        Total DAP:
        {{ generalstudymoduleattr.projectionxrayradiationdose_set.get.accumxraydose_set.get.accumintegratedprojradiogdose_set.get.convert_gym2_to_cgycm2|floatformat:1 }}
        cGy.cm<sup>2</sup>
    </li>
</ul>

<table class="table table-striped table-bordered">
    <th>Time</th>
    <th>Protocol</th>
    <th>View</th>
    <th>kVp</th>
    <th>mAs</th>
    <th>mA</th>
    <th>Time<br>(ms)</th>
    <th>Filters<br>(mm)</th>
    <th>SID<br>(mm)</th>
    <th>Grid FD<br>(mm)</th>
    <th>Exposure Index<br>IEC</th>
    <th>Exposure Index<br>vendor</th>
    <th>DAP<br>(cGy.cm<sup>2</sup>)</th>
    <th>Control mode</th>
    <th>Comment</th>
    {% for event in generalstudymoduleattr.projectionxrayradiationdose_set.get.irradeventxraydata_set.all %}
    <tr>
        <td>{{ event.date_time_started|time:"H:i.s" }}</td>
        <td>{{ event.acquisition_protocol }}</td>
        <td>{{ event.image_view }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.kvp_set.get.kvp|floatformat:0 }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.exposure_set.get.convert_uAs_to_mAs|floatformat:1 }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.average_xray_tube_current|floatformat:0 }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.exposure_time|floatformat:0 }}</td>
        <td>
            {% for xrayfilt in event.irradeventxraysourcedata_set.get.xrayfilters_set.all %}
                {% if xrayfilt.xray_filter_material.code_value == 'C-120F9' %}
                    Al: {{ xrayfilt.xray_filter_thickness_minimum }} - {{ xrayfilt.xray_filter_thickness_maximum }} <br>
                {% elif xrayfilt.xray_filter_material.code_value == 'C-127F9' %}
                    Cu: {{ xrayfilt.xray_filter_thickness_minimum }} - {{ xrayfilt.xray_filter_thickness_maximum }} <br>
                {% else %}
                    {{ xrayfilt.xray_filter_material.code_meaning }}: {{ xrayfilt.xray_filter_thickness_minimum }} - {{ xrayfilt.xray_filter_thickness_maximum }} <br>
                {% endif %}
            {% endfor %}
        </td>
        <td>{{ event.irradeventxraymechanicaldata_set.get.doserelateddistancemeasurements_set.get.distance_source_to_detector|floatformat:0 }}</td>
        <td>
            {{ event.irradeventxraysourcedata_set.get.grid_focal_distance|floatformat:0 }}
        </td>
        <td>
            EI: {{ event.irradeventxraydetectordata_set.get.exposure_index|floatformat:1 }} <br>
            EI<sub>T</sub>: {{ event.irradeventxraydetectordata_set.get.target_exposure_index|floatformat:1 }} <br>
            DI: {{ event.irradeventxraydetectordata_set.get.deviation_index|floatformat:1 }}
        </td>
        <td>
            {{ event.irradeventxraydetectordata_set.get.relative_xray_exposure|floatformat:0 }}
            {{ event.irradeventxraydetectordata_set.get.relative_exposure_unit }}
        </td>
        <td>{{ event.convert_gym2_to_cgycm2|floatformat:1 }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.exposure_control_mode }}</td>
        <td>{{ event.comment }}</td>
    </tr>
    {% endfor %}
</table>



{% endblock %}	

openrem/remapp/templates/remapp/mgdetail.html
{% extends "remapp/base.html" %}

{% block navbar %}
            {% if request.user.userprofile.displayCT %}<li><a href="/openrem/ct">CT</a></li>{% endif %}
            {% if request.user.userprofile.displayRF %}<li><a href="/openrem/rf">Fluoroscopy</a></li>{% endif %}
            {% if request.user.userprofile.displayMG %}<li class="active"><a href="/openrem/mg">Mammography</a></li>{% endif %}
            {% if request.user.userprofile.displayDX %}<li><a href="/openrem/dx">Radiography</a></li>{% endif %}
{% endblock %}


{% block mainblock %}		
<h1>Detail list of events</h1>

<ul>
    <li>Accession number: {{ generalstudymoduleattr.accession_number }}</li>
    <li>Study date: {{ generalstudymoduleattr.study_date }}</li>
    <li>Study time: {{ generalstudymoduleattr.study_time }}</li>
    <li>Study description: {{ generalstudymoduleattr.study_description }}</li>
    <li>Requested procedure: {{ generalstudymoduleattr.requested_procedure_code_meaning }}</li>
    <li>Patient age: {{ generalstudymoduleattr.patientstudymoduleattr_set.get.patient_age_decimal|floatformat:1 }}</li>
    <li>Hospital: {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.institution_name }}</li>
    <li>
        Scanner: 
        {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.manufacturer }} |
        {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.manufacturer_model_name }} |
        {{ generalstudymoduleattr.generalequipmentmoduleattr_set.get.station_name }}
    </li>
    <li>Study UID: {{ generalstudymoduleattr.study_instance_uid }}</li>
    <li>Test patient indicators? {{ generalstudymoduleattr.patientmoduleattr_set.get.not_patient_indicator }}</li>
</ul>

<table class="table table-striped table-bordered">
    <th>Time</th>
    <th>Acquisition protocol</th>
    <th>View</th>
    <th>Compression thickness</th>
    <th>Target</th>
    <th>Filter</th>
    <th>kVp</th>
    <th>mA</th>
    <th>Exposure time</th>
    <th>ESD</th>
    <th>AGD (mGy)</th>
    {% for event in generalstudymoduleattr.projectionxrayradiationdose_set.get.irradeventxraydata_set.all %}
    <tr>
        <td>{{ event.date_time_started|time:"H:i.s" }}</td>
        <td>{{ event.acquisition_protocol }}</td>
        <td>{{ event.image_view }}</td>
        <td>{{ event.irradeventxraymechanicaldata_set.get.compression_thickness|floatformat:0  }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.anode_target_material }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.xrayfilters_set.get.xray_filter_material }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.kvp_set.get.kvp|floatformat:0 }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.average_xray_tube_current|floatformat:1 }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.exposure_time|floatformat:1 }}</td>
        <td>{{ event.entrance_exposure_at_rp|floatformat:3 }}</td>
        <td>{{ event.irradeventxraysourcedata_set.get.average_glandular_dose|floatformat:3 }}</td>
    </tr>
    <tr>
        <td colspan = "11"><small> <strong>Exposure Control Mode Description:</strong>{{ event.comment }} </small></td>
    </tr>
    {% endfor %}
</table>



{% endblock %}	